### ISSUE TITLE
[Batman] Som en netvirksomhed vil jeg kunne modtage beskeder som indeholder resultater for total forbrug pr time/kvarter i besked formatet CIM-XML

### ISSUE THREAD

**Issue by Christian-Meyer** [Energinet-DataHub/opengeh-edi#11]
**As a balance supplier**
We want to be able to receive a message containing the results for non profiled consumption pr. grid area in CIM XML format
So that we can ensure the balance on our metering points.  

**Description**
The purpose of this feature is to enable the balance supplier to receive the results of a specific calculation. The balance supplier must be able to receive the results in CIM XML format. They will receive them by peeking the message from our queue.
https://energinet.sharepoint.com/:u:/r/sites/DH3ART-team/Delte%20dokumenter/General/CIM/CIM%20XSD%20-%20XML/XML%20filer/XML%2020220706%20-%20Danske%20koder%20-%20v.1.5/Notify%20aggregated%20measure%20data.xml?csf=1&web=1&e=xxEOk1

**Test**
We want to test it by peeking and validating if the message is received and if it contains the correct information.

**Acceptance criteria**

- [x] When the balance supplier peeks they receive a notify aggregated measure data message in CIM XML format. (Assuming there is a message for them) 
- [x] When the balance supplier dequeues the message is deleted
- [x] The message must adhere to schema

**Tasks**
- [x] Adjust document writer - 1 PED
- [x] Refactor `AggregationResult` - 1 PED
- [x] Refactor handling to use integration event - 2 PED

**Comment by Christian-Meyer** [comment]
Done
