### ISSUE TITLE
[Batman]Som en balance ansvarlig vil jeg kunne modtage beskeder som indeholder resultatet af aggregeret forbrug i besked formatet CIM-XML

### ISSUE THREAD

**Issue by Christian-Meyer** [Energinet-DataHub/opengeh-edi#12]
As a balance responsible party
We want to be able to receive a message containing the results for a non-profiled calculated consumption MP in CIM XML format
So that we can calculate how we need to bill the energy supplier and to balance how much we need to buy and sell at Nordpool

**Description**
The purpose of this feature is to enable the balance responsible party to receive the results of a specific calculation. The balance responsible party must be able to receive the results in CIM XML format. They will receive them by peeking the message from our queue.

**Test**
We want to test it by peeking  and validating if the message is received and if it contains the correct information.

**Acceptance criteria**

- [ ] When the balance responsible party peeks they receive a notify aggregated measure data message in CIM XML format. (Assuming there is a message for them) 
- [ ] When the balance responsible party dequeues the message is deleted

**Tasks**
- [x] Add attributes to NotififyAggregatedMeasureData. "energySupplier_MarketParticipant.mRID" and "balanceResponsibleParty_MarketParticipant.mRID" be included if present in MessageRecord, and excluded if not (1 PED)

- [x] Include energy supplier number in AggregationResult metadata. This is required for consumption result targeted balance suppliers (1 PED)

- [x] Start transaction when a non-profiled consumption result is available. (1 PED)

- [x] Extend wholesale API service (AggreationResultsOverHttp) to support fetching non-profiled consumption per. balance responsible (1 PED)

- [x] Translate qualitycode from wholesale to EDI

A02 => missing
A03 => estimated
A04 => measured
A05 => incomplete
A06 => calculated
