### ISSUE TITLE
Be able to search messages when pressing search

### ISSUE THREAD

**Issue by Christian-Meyer** [Energinet-DataHub/opengeh-edi#212]
As a DH user
I want to be able to search messages in the frontend when pressing search (marked below)

![image.png](https://images.zenhubusercontent.com/60bf67953ffc7e5c3e70b6a8/2f1651cc-49af-4a0a-8ca8-cf0433809837)

**AC**
- [x]  When I press search I am shown all available messages. Results are displayed as below

![image.png](https://images.zenhubusercontent.com/60bf67953ffc7e5c3e70b6a8/55b64e33-269f-41a7-82d7-09f8dbaf693e)

**Tasks**
- [x] Message query - 1 PEW 
- [x] Wireup BFF and frontend – 3 PED

**Comment by Christian-Meyer** [comment]
I am looking into what text should be displayed if no results are found.
