### ISSUE TITLE
As a user only my own messages are displayed

### ISSUE THREAD

**Issue by Christian-Meyer** [Energinet-DataHub/opengeh-edi#219]
As a DH user
I am only allowed to view my own messages
So that I cannot view other actors messages

Denne dækker ikke over søgeparametrerne. 
Gælder både for modtager og afsender. 

**AC**
- [x] As a user I can use all search criteria, but I am only allowed to view my own messages. I should not be able to access or view other users messages. 

**Risk (L/M/H)**
H

Konsekvens?
Det ville være rigtig kritisk hvis aktører fik adgang til andre aktørers data. 

**DoR**
- [x] Er opgaven tilstrækkeligt beskrevet (Forstår vi hvad der skal laves, hvorfor vi gør det og hvordan vi lykkes)
- [x] Er der klare acceptance criteria - som er testbare
- [x] Har vi de nødvendige kompetencer (pre-refinement)
- [x] Risikovurdering i hvor udstrækning kan denne dækkes af automatiske test - H, M L (Pre-refinement)
- [x] Er opgaven estimeret af teamet i forhold til forventet kompleksitet (Hvis høj skal den skæres anderledes eller er der noget der skal uddybes)

**Tasks**
- [x] Extend search to filter to include the requestor 
- [x] Set requestor if request is not a ENDK user
- [x] building block configuration

**DoD**
Udvikler
- [x] Udvikling færdiggjort
- [x] Accept kriterier er opfyldt
- [x] Dokumentation oprettet eller opdateret hvis relevant for opgaven
   - [ ] Teknisk dokumentation 
   - [ ] C4 
- [x] Test link vedhæftet til QA acceptance 
QA
- [ ] Testet om Accept kriterierne er opfyldt
- [ ] Dokumentation lavet på test
PO
- [ ] PO accept
- [ ] Demo for relevante stakeholders (Er dette kandidat til GreenForce demo?)

**Comment by MadsDue** [comment]
Tests:
https://github.com/Energinet-DataHub/opengeh-edi/pull/630/files#diff-240fa6946b4bc37060fd4be75842b9e2ed97a03ba7b2bab9e700952e7af8e13d
